// Package material 素材管理相关API
//
// https://work.weixin.qq.com/api/doc#90000/90135/91054
package material

import (
	wechatwork "github.com/dfang/wechat-work-go"
)

type Material struct {
	App *wechatwork.App
}

type AutoGenerated struct {
	Errcode   int    `json:"errcode"`
	Errmsg    string `json:"errmsg"`
	Type      string `json:"type"`
	MediaID   string `json:"media_id"`
	CreatedAt string `json:"created_at"`
}

// UploadMedia 上传临时素材
//
// https://work.weixin.qq.com/api/doc#90000/90135/90253
func (m Material) UploadMedia(mediaType string) {
	// apiPath:="cgi-bin/media/upload"
	// uri := fmt.Sprintf("%s?access_token=%s&type=%s", apiPath, menu.App.GetAccessToken(), mediaType)
}

// UploadImg 上传永久图片
//
// https://work.weixin.qq.com/api/doc#90000/90135/90256
func (m Material) UploadImg() {
	// apiPath:="cgi-bin/media/uploadimg"
	// uri := fmt.Sprintf("%s?access_token=%s", apiPath, menu.App.GetAccessToken())
}

// GetMedia 获取临时素材
//
// https://work.weixin.qq.com/api/doc#90000/90135/90254
func (m Material) GetMedia(mediaID string) {
	// apiPath:="cgi-bin/media/get"
	// uri := fmt.Sprintf("%s?access_token=%s&media_id=%s", apiPath, menu.App.GetAccessToken(), mediaID)
}

// GetVoice 获取高清语音素材
//
// https://work.weixin.qq.com/api/doc#90000/90135/90255
func (m Material) GetVoice(mediaID string) {
	// apiPath:="cgi-bin/media/get/jssdk"
	// uri := fmt.Sprintf("%s?access_token=%s&media_id=%s", apiPath, menu.App.GetAccessToken(), mediaID)
}
