package models

import "encoding/json"

// 创建自定义菜单
type ReqMenuCreate struct {
	Button []struct {
		Name      string `json:"name"`
		Type      string `json:"type,omitempty"`
		Key       string `json:"key,omitempty"`
		SubButton []struct {
			Type      string        `json:"type"`
			Name      string        `json:"name"`
			Key       string        `json:"key"`
			URL       string        `json:"url,omitempty"`
			SubButton []interface{} `json:"sub_button"`
		} `json:"sub_button,omitempty"`
	} `json:"button"`
}

// type ButtonItem struct {
// 	Name string `json:"name"`
// 	Type string `json:"type,omitempty"`
// }

// type AutoGenerated struct {
// 	Button []struct {
// 		Type      string `json:"type,omitempty"`
// 		Name      string `json:"name"`
// 		Key       string `json:"key,omitempty"`
// 		SubButton []struct {
// 			Type string `json:"type"`
// 			Name string `json:"name"`
// 			URL  string `json:"url,omitempty"`
// 			Key  string `json:"key,omitempty"`
// 		} `json:"sub_button,omitempty"`
// 	} `json:"button"`
// }

// Menu 菜单
type Menu struct {
	Button []Button `json:"button"`
}

// Button 菜单项
type Button struct {
	Name      string      `json:"name"`
	SubButton []SubButton `json:"sub_button,omitempty"`
	Type      string      `json:"type,omitempty"`
	Key       string      `json:"key,omitempty"`
}

// SubButton 子菜单项
type SubButton struct {
	Type      string        `json:"type"`
	Name      string        `json:"name"`
	Key       string        `json:"key,omitempty"`
	URL       string        `json:"url,omitempty"`
	SubButton []interface{} `json:"sub_button,omitempty"`
}

func (x Menu) IntoBody() ([]byte, error) {
	result, err := json.Marshal(x)
	if err != nil {
		return nil, err
	}
	return result, nil
}
